import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import FileExplorer from "./components/FileExplorer";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  weight: ["300", "400", "500", "700", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.className}>
      <body className="w-screen h-screen">
        <main className="flex w-full h-full items-center justify-center">
          <FileExplorer />
          {children}
        </main>
      </body>
    </html>
  );
}
